version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: phoenix_live_reload
    versions:
    - 1.3.1
  - dependency-name: ecto_sql
    versions:
    - 3.6.0
    - 3.6.1
  - dependency-name: floki
    versions:
    - 0.30.1
  - dependency-name: hackney
    versions:
    - 1.17.4
  - dependency-name: phoenix
    versions:
    - 1.5.8
  - dependency-name: observer_cli
    versions:
    - 1.6.1
  - dependency-name: sentry
    versions:
    - 8.0.5
  - dependency-name: phoenix_live_view
    versions:
    - 0.15.4
- package-ecosystem: npm
  directory: "/apps/thundermoon_web/assets"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
  - dependency-name: chart.js
    versions:
    - 3.0.2
    - 3.1.0
    - 3.1.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.15
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: parcel-plugin-static-files-copy
    versions:
    - 2.5.1
    - 2.6.0
  - dependency-name: parcel-bundler
    versions:
    - 1.12.5
  - dependency-name: sass
    versions:
    - 1.32.5
    - 1.32.6
    - 1.32.7
    - 1.32.8
