version: '3.7'
services:
  app:
    image: $IMAGE
    env_file:
     - .env/app
    environment:
      PORT: 4000
      DB_HOST: db
      DB_DATABASE: thundermoon_prod
      DB_USER: thundermoon
    ports:
      - "80:4000"
    volumes:
      - ./log:/app/log
    depends_on:
      - db
    command: sh -c './wait-for.sh db:5432 -- ./run.sh'
      
  db:
    image: postgres:11.3-alpine
    env_file:
     - .env/db
    environment:
      POSTGRES_USER: thundermoon
      POSTGRES_DB: thundermoon_prod
      PG_DATA_DIR: data
    volumes:
      - ./data:/var/lib/postgresql/data