version: "3.7"
services:
  app:
    image: $IMAGE
    user: elixir:elixir
    env_file:
      - .env_files/app
    environment:
      PORT: 4000
    ports:
      - "4000:4000"
    volumes:
      - ./log:/app/log
    depends_on:
      - db
      - web
    command: sh -c './wait-for.sh db:5432 -- ./run.sh'

  db:
    image: postgres:16.3-alpine
    env_file:
      - .env_files/db
    environment:
      POSTGRES_USER: thundermoon
      POSTGRES_DB: thundermoon_prod
      PG_DATA_DIR: data
    volumes:
      - ./data:/var/lib/postgresql/data
      - /srv/backup/weekly/thundermoon.zero-x.net:/import

  web:
    image: caddy:2.8-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /srv/sites/thundermoon.zero-x.net/Caddyfile:/etc/caddy/Caddyfile
      #- ./site:/srv # static files
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - ipv6pub

volumes:
  caddy_data:
  caddy_config:

networks:
  ipv6pub:
    enable_ipv6: true
